server:
  port: 8761

spring:
  application:
    name: demo-eureka-server

eureka:
  instance:
    hostname: localhost
  server:
    wait-time-in-ms-when-sync-empty: 0
    use-read-only-response-cache: false
    response-cache-update-interval-ms: 5000
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
